name: Run Robot Tests

on: [push]

jobs:
  run-robot-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install robotframework
          pip install robotframework-requests

      - name: Run Robot tests
        run: robot test_consultaCNPJ.robot